"""adding html for posts

Revision ID: 04c4d7b09b74
Revises: 1014d2921207
Create Date: 2021-01-18 19:02:18.391874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c4d7b09b74'
down_revision = '1014d2921207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'body_html')
    # ### end Alembic commands ###
