"""add info of profile

Revision ID: 64afcb252030
Revises: 0e36f8d6c2d9
Create Date: 2021-01-14 18:48:20.632840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64afcb252030'
down_revision = '0e36f8d6c2d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Location', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('menber_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    op.drop_column('users', 'menber_since')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'about_me')
    op.drop_column('users', 'Location')
    # ### end Alembic commands ###
