"""editing

Revision ID: 6e9e3f89ed9f
Revises: c3fb62bc65f2
Create Date: 2021-01-20 11:22:23.413060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e9e3f89ed9f'
down_revision = 'c3fb62bc65f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'Posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['post_id'], ['id'])
    # ### end Alembic commands ###
